<a href="https://colab.research.google.com/github/Z-Toya/deep_learning_note/blob/main/code/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [ ]:
arr = np.array([1, 'hello'])
print(arr)

['1' 'hello']


In [ ]:
arr = np.array([1,2,3])
print(arr.ndim)
print(arr)

1
[1 2 3]


In [ ]:
# 全0 全1 未初始化 固定值
arr1 = np.zeros((2,),dtype=int)
arr2 = np.zeros((2,3),dtype=int)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 全1
arr = np.ones((5,),dtype=int)
print(arr)

[1 1 1 1 1]


In [ ]:
# 未初始化
arr = np.empty((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.full((3,4),2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [ ]:
arr1 = np.zeros_like(arr)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
# 等差数列
arr = np.arange(1,10,1) # start,end,step
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 等间隔数列
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
# 对数间隔数列
arr = np.logspace(0,4,2,base=2)
print(arr)

arr = np.logspace(0,4,3,base=2)
print(arr)

[ 1. 16.]
[ 1.  4. 16.]


In [ ]:
# 特殊矩阵
# 单位矩阵
arr = np.eye(3,4,dtype=int) # 不加后面的4就是方阵
print(arr)

# 对角矩阵
arr = np.diag([1,2,3])
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3)
print(arr)

# 生成指定范围区间内的随机浮点数（均匀分布）
arr = np.random.uniform(3,6,(2,3))
print(arr)

[[0.29965968 0.81254775 0.00289498]
 [0.06621712 0.92451074 0.88306852]]
[[5.96293233 3.92376248 5.42026115]
 [3.2786077  5.5069818  3.91766106]]


In [ ]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3,30,(2,3))
print(arr)

[[29 13  4]
 [ 3  7 28]]


In [ ]:
# 生成随机数列（正态分布）
arr = np.random.randn(2,3)
print(arr)

[[-1.12423669 -0.20021014 -0.72611745]
 [-1.38210366 -0.58444512 -1.6302119 ]]


In [ ]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


In [6]:
# 一维数组的索引与切片
arr = np.random.randint(1,100,20)
print(arr)
print(arr[10])
print(arr[:]) # 获取全部的数据
print(arr[2:5]) # start:end+1 作闭右开区间
print(arr[slice(2,15,3)]) # start,end,step
print(arr[ (arr>10) & (arr<70) ]) # 布尔索引

[64 25 78 70 85 90 29 31 33 53 23 77 85 48 33 49 51 35 82 38]
23
[64 25 78 70 85 90 29 31 33 53 23 77 85 48 33 49 51 35 82 38]
[78 70 85]
[78 90 33 77 33]
[64 25 29 31 33 53 23 48 33 49 51 35 38]


# 二维数组的索引与切片
arr = np.random.randint(1,100,(4,8))
print(arr)
print(arr[1,3])
print(arr[:,:]) # 获取全部数据
print(arr[1,2:5])
print(arr[arr>50]) # 返回一维的结果
print(arr[2][arr[2]>50]) # 返回第三行大于50的元素，注意嵌套
print(arr[:,3]) # 返回第四列\\